### ISSUE TITLE
infinite loop with CR

### ISSUE THREAD

**Issue by nobu** [rdoc/rdoc#339]
An infinite loop bug was reported at [ruby-dev:48813](https://bugs.ruby-lang.org/issues/10732).

The following hangs up.
~~~
echo -e '\ra\t' > dummy.txt
rdoc dummy.txt
~~~

Fixed at [r49223](http://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=49223), ruby/ruby@77f3125567adc54b8a5534c2c1ded5a19100e8d5

**Comment by hsbt** [comment]
@nobu I backported r49223. Thanks!
