### ISSUE TITLE
Markup bug

### ISSUE THREAD

**Issue by salogorilka** [rdoc/rdoc#343]
There is a mistake (I think it's a markup error) in documentation about String#tr method.
http://ruby-doc.org/core-2.2.0/String.html#method-i-tr

         The backslash character </code> can be used to escape <code>^ or -

 It need to be fixed.

**Comment by zzak** [comment]
I'm guessing this has to do with the escaping character, but I'm not sure how to fix it yet.

Thanks for your report!

**Comment by zzak** [comment]
This was actually a bug in the documentation of this method, and fixed in the release of Ruby 2.3.0 by ruby/ruby#1063!
