### ISSUE TITLE
Missing files in Rdoc

### ISSUE THREAD

**Issue by xuanzhaopeng** [rdoc/rdoc#347]
Hi,

I try a lot of way to generate RDoc with JRuby 1.7.15 and 1.7.18, by following command

"C:\Program Files\Java\jdk1.7.0_71\jre\bin\java.exe" -cp "jruby-complete-1.7.15.jar" org.jruby.Main -S rake rdoc

the Rake file is :
require 'rubygems'
require 'rdoc'
require 'rake/clean'
require 'rdoc/task'

CLEAN.include("pkg")

RDoc::Task.new do |rd|
  rd.rdoc_files.include("Rakefile", "README.txt", "CHANGELOG.txt", "bin/**/*.rb", "lib/**/*.rb")
  rd.main = "README.txt"
  rd.title = 'hello'
  rd.rdoc_dir = 'docs'
  rd.options << "--all"
end

but it always propose an error :

No such file or directory - No such file or directory - file:C:/Users/MYNAME/Desktop/Rake/jruby-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/rdoc/generator/
template/darkfish/file:C:/Users/MYNAME/Desktop/Rake/jruby-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/rdoc/generator/template/darkfish/js/darkfish.js

I try same command in JRuby 1.7.18, with the same error but other files missing.

PS: I have verified the file is exist in the jruby-complete-1.7.15.jar

Could you help me for it, thanks a lot!!

**Comment by drbrain** [comment]
Does File work transparently with files in a jar on JRuby?

**Comment by zzak** [comment]
Unknown, any ideas? @headius @enebo

**Comment by headius** [comment]
It has worked somewhat in the past and should work significantly better in JRuby 9k. The error above appears to be an issue calculating a relative path for a "file" URL inside the JRuby jar. This should work better now.

```
[] ~/projects/jruby/tmp/tmp2 $ cat Rakefile 
require 'rubygems'
require 'rdoc'
require 'rake/clean'
require 'rdoc/task'

CLEAN.include("pkg")

RDoc::Task.new do |rd|
rd.rdoc_files.include("lib//*.rb")
rd.main = "README.txt"
rd.title = 'hello'
rd.rdoc_dir = 'docs'
rd.options << "--all"
end

[] ~/projects/jruby/tmp/tmp2 $ ls lib
blah.rb

[] ~/projects/jruby/tmp/tmp2 $ java -jar ~/Downloads/jruby-complete-9.0.5.0-SNAPSHOT.jar -S rake rdoc
Parsing sources...
100% [ 1/ 1]  lib//blah.rb                                                      

Generating Darkfish format into /Users/headius/projects/jruby/tmp/tmp2/docs...
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rdoc/method_attr.rb:184: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rdoc/method_attr.rb:184: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.

  Files:      1

  Classes:    1 (1 undocumented)
  Modules:    0 (0 undocumented)
  Constants:  0 (0 undocumented)
  Attributes: 0 (0 undocumented)
  Methods:    1 (1 undocumented)

  Total:      2 (2 undocumented)
    0.00% documented

  Elapsed: 0.9s
```

I'd recommend closing this. It could be refiled as a JRuby 1.7.x issue, but only if JRuby 1.7.23 fails...and even then, we might not fix it since it's working in JRuby 9k.

**Comment by zzak** [comment]
@headius Thanks for your report! I will close this unless someone is willing to fix it.
