### ISSUE TITLE
errors with <visibility> def ... (ruby >= 2.1)

### ISSUE THREAD

**Issue by thyresias** [rdoc/rdoc#354]
With the code below:
* method X::Y#foo is not documented
* class X::Z is documented as Z, with superclass Y (instead of X::Z < X::Y)
```ruby
module X
  class Y
    protected def foo
    end
  end
  class Z < Y
    def foo
    end
  end
end
```

**Comment by zzak** [comment]
Going to close this in favor of #355, since I might be able to get @senny to help out with this one ;)
