### ISSUE TITLE
<visibility> def hides following methods

### ISSUE THREAD

**Issue by senny** [rdoc/rdoc#355]
xref #354

Just noticed that [this `private def` definition](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L607) removed all following methods from the docs.

**Comment by zzak** [comment]
Thanks for the report! I'll see what we can do about fixing this one.

**Comment by zzak** [comment]
Sorry we didn't have time to get this in the next patch release.

**Comment by aangoulvant** [comment]
Would add a +1 on this one - would be great if this could be addressed
