### ISSUE TITLE
Rdoc does not serve darkfish CSS 

### ISSUE THREAD

**Issue by awood** [rdoc/rdoc#359]
Hi,

I'm running on Fedora 22, and when I run `ri --serve` the generated rdoc requests `/css/rdoc.css` which the WEBrick servlet cannot find.

My procedure to reproduce is

1. `sudo dnf install ruby-devel rubygem-rdoc`
2. `gem install highline --ri --rdoc`
3. `ri --serve`

When I go to localhost:8214, the page is served but the CSS cannot be found.  Here are the relevant messages from WEBrick

```
[2015-07-31 11:42:41] INFO  WEBrick 1.3.1
[2015-07-31 11:42:41] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2015-07-31 11:42:41] INFO  WEBrick::HTTPServer#start: pid=3552 port=8214
localhost.localdomain - - [31/Jul/2015:11:42:56 EDT] "GET / HTTP/1.1" 200 3200
- -> /
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /css/fonts.css HTTP/1.1" 404 2048
http://localhost:8214/ -> /css/fonts.css
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /css/rdoc.css HTTP/1.1" 404 2048
http://localhost:8214/ -> /css/rdoc.css
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /js/search_index.js HTTP/1.1" 200 361
http://localhost:8214/ -> /js/search_index.js
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /favicon.ico HTTP/1.1" 404 2056
- -> /favicon.ico
```

I see in the [darkfish template](https://github.com/rdoc/rdoc/blob/master/lib/rdoc/generator/template/darkfish/_head.rhtml#L13) that the CSS is being served off `css/rdoc.css`, but in the [servlet.rb](https://github.com/rdoc/rdoc/blob/master/lib/rdoc/servlet.rb#L117), the case statement is matching on `/rdoc.css`

There are also some problems with the JS when I request the rdoc for an actual gem:

```
localhost.localdomain - - [31/Jul/2015:11:52:02 EDT] "GET /highline-1.7.2/js/navigation.js HTTP/1.1" 404 3912
http://localhost:8214/highline-1.7.2/ -> /highline-1.7.2/js/navigation.js
localhost.localdomain - - [31/Jul/2015:11:52:02 EDT] "GET /highline-1.7.2/js/searcher.js HTTP/1.1" 404 3910
localhost.localdomain - - [31/Jul/2015:11:52:02 EDT] "GET /highline-1.7.2/js/search.js HTTP/1.1" 404 3908
```

**Comment by awood** [comment]
The problems with the JS are located in `darkfish.js`.  `servlet.rb` is only equipped to handle requests like `/js/search.js` but the `req.path` coming in is `/highline-1.6.21/js/search.js`

**Comment by zzak** [comment]
I think this was caused by #335... sorry!
