### ISSUE TITLE
lib/rdoc/i18n files are not included in the 4.2.0 gem

### ISSUE THREAD

**Issue by graaff** [rdoc/rdoc#362]
The files in lib/rdoc/i18n and lib/rdoc/generator/pot are not included in the gem for 4.2.0, even though the tests referring to them are. This leads to test failures like:

```
test_translate_existent_message(TestRDocI18nLocale):
LoadError: cannot load such file -- rdoc/i18n
    /var/tmp/portage/dev-ruby/rdoc-4.2.0/work/ruby19/rdoc-4.2.0/test/test_rdoc_i18n_locale.rb:70:in `locale'
    /var/tmp/portage/dev-ruby/rdoc-4.2.0/work/ruby19/rdoc-4.2.0/test/test_rdoc_i18n_locale.rb:7:in `setup'
```

**Comment by zzak** [comment]
I haven't seen these failures myself.

@kou Any ideas?

**Comment by kou** [comment]
Use #374.

**Comment by tjkirch** [comment]
The missing files in lib/rdoc/generator/pot/ are still a problem in the 4.2.1 gem.  They do exist if you download the 4.2.1 tagged release from github, but the manifest needs a fix for lib/rdoc/generator/pot/.
