### ISSUE TITLE
Ignore frozen-string-literal magic comment

### ISSUE THREAD

**Issue by jeremyevans** [rdoc/rdoc#389]
`frozen-string-literal` magic comments are parsed and appear in the rdoc output as text in the file level comment.  This can result in the ignoring of a file level comment that comes after the magic comment, if there is a line of whitespace between the magic comment line and the file level comment.

**Comment by zzak** [comment]
Nice, sorry I missed this one.

Thanks for the report!

**Comment by halostatue** [comment]
I don’t often have file-level comments, but as I don’t typically use the Seattle-style for my class comments (below), I end up with `frozen_string_literal: true` in the documentation for the first class or module in the file.

```ruby
# Not Seattle-style.
class Foo; end

##
# Seattle-style.
class Bar; end
```

If I nest namespaces in a bunch of files, I end up with `frozen_string_literal: true` in the documentation for the outer namespace for each file that has this construct:

```ruby
# frozen_string_literal: true

module Namespace
  # A class that I care about.
  class ThatICareAbout
  end
end
```

Each file that contains `Namespace` without the “hey! here’s a documentation comment” marker (the Seattle-style `##`) results in `frozen_string_literal: true` being added to the top of the `Namespace` documentation.
