### ISSUE TITLE
Create 4.2.2 release to fix missing files in 4.2.1

### ISSUE THREAD

**Issue by tjkirch** [rdoc/rdoc#394]
I'd like to request that a 4.2.2 release be created because the 4.2.1 gem was missing files -- see #391.

I've created PR #393 for the basic file changes.  I'm not sure what else is involved, but I thought a tracking issue might help.  Thanks!

**Comment by hsbt** [comment]
@drbrain @zzak Can you make hsbt at ruby-lang.org rdoc gem owner? I will release rdoc-4.2.2.

**Comment by drbrain** [comment]
@hsbt: done

**Comment by hsbt** [comment]
@drbrain Thank you!

@tjkirch Released rdoc-4.2.2
