### ISSUE TITLE
RDoc 4.3

### ISSUE THREAD

**Issue by zzak** [rdoc/rdoc#395]
This ticket will be a discussion/place to tag tickets for the next minor release of RDoc, version 4.3.0.

**Comment by zzak** [comment]
- [ ] Replace hoe with bundler `bundler/gem_helper` tasks /cc #396 
- [ ] Replace lib/markdown with kramdown (since kramdown is now MIT)

**Comment by hsbt** [comment]
> Replace lib/markdown with kramdown (since kramdown is now MIT)

It seems breaking changes to me. Should we add this feature to rdoc-5.0?

**Comment by zzak** [comment]
@hsbt Yes, also I'm still considering

**Comment by halostatue** [comment]
I’d love to see #389 fixed for 4.3 (I just added more comments to hopefully boost its priority).

**Comment by drbrain** [comment]
AFAIK `bundler/gem_helper` is not a replacement for `hoe`, so we should not remove it.  It seems it would make maintenance of the Rakefile more complicated and spread across more files.

**Comment by hsbt** [comment]
@zzak any progress?

We planned to release 2.4preview1 at next week. I hope to merge @mame 's improvement to ruby trunk while 1 month. Can we merge rdoc 4.3 into 2.4preview1?

**Comment by zzak** [comment]
Sorry I missed this, I will try to make preview 2 :)

**Comment by zzak** [comment]
@drbrain I want to remove hoe to make it easier for testing plugins and third-party extensions against master.

>  It seems it would make maintenance of the Rakefile more complicated and spread across more files.

In fact, removing hoe actually [simplified the Rakefile](https://github.com/rdoc/rdoc/pull/396/files#diff-52c976fc38ed2b4e3b1192f8a8e24cff) and reduced the number of dependencies, which should make maintenance simpler.

Not only does this allow testing extensions and plugins easier, but also contributors will have a much more familiar workflow to contribute; which IMO is the biggest benefit and worth the complexity of moving parser generation onto our Rakefile.

**Comment by shaneog** [comment]
Will 4.3.0 still require `json` ~1.x or will the dependency be relaxed to also allow [json 2.x](https://github.com/flori/json/blob/master/CHANGES.md#2015-09-11-200) which has been released.

**Comment by hsbt** [comment]
@zzak I'm going to develop and release to rdoc 4.3 and 5.0 at Aug, 2016. I can't wait it releases. If you have some concerns, Please mention to me.

**Comment by zzak** [comment]
@hsbt What is the purpose for 5.0?

**Comment by hsbt** [comment]
@zzak Remove dependency of json for https://github.com/rdoc/rdoc/issues/395#issuecomment-230154585, and drop Ruby 1.8 support. It is breaking changes.

**Comment by zzak** [comment]
@hsbt Sounds good, can we open a ticket like this one for version 5.0?

**Comment by hsbt** [comment]
@zzak Any progress? If you have some issues, I will help you.

**Comment by zzak** [comment]
@hsbt Thanks! I will check if there are any major blockers and release in the next week or two.

Then we can work on 5.0, including the Ruby version support changes!

**Comment by zzak** [comment]
I've decided since there is limited time, that we should cut what we have as 5.0 starting with a pre-release before RubyKaigi that can make it into Ruby 2.4.0 preview 2 (hopefully).

**Comment by hsbt** [comment]
We will discuss on https://github.com/rdoc/rdoc/issues/413 continuously.
