### ISSUE TITLE
RDoc 5.0

### ISSUE THREAD

**Issue by zzak** [rdoc/rdoc#413]
- [ ] [json dependency](https://github.com/rdoc/rdoc/issues/395#issuecomment-230154585): #412
- [ ] Drop Ruby 1.8 support
- [ ] #395

**Comment by zzak** [comment]
@hsbt What are your plans for the json dependency?

I think we're using it for JSONIndex stuff, which I'd like to keep in RDoc if possible.

**Comment by zzak** [comment]
Ahh, I just saw #412

**Comment by hsbt** [comment]
@zzak I added comment for that issue.
