### ISSUE TITLE
request to follow SemVer/update README.

### ISSUE THREAD

**Issue by pravi** [rdoc/rdoc#427]
If you follow SemVer, it makes life much easier for me to maintain gitlab in debian. Without this guarantee I cannot update rdoc to latest upstream release with confidence that it does not break gitlab. For example right now debian has rdoc 4.2.1, but gitlab is still on 3.6 (and moving to ~> 4.2.0 https://gitlab.com/gitlab-org/gitlab-ce/issues/2814). If you declare SemVer compliance, then they can relax it to just ~> 4.2 and I can always update to latest 4.x release in debian without maintaining a patch for gitlab. So please consider following SemVer.

**Comment by drbrain** [comment]
RDoc follows semantic versioning.  If there has been API breakage without a major version change it is a bug, please file it.
