### ISSUE TITLE
rake build fails

### ISSUE THREAD

**Issue by dogatana** [rdoc/rdoc#432]
rake build fails.

```
> rake build
rake aborted!
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["lib/rdoc/markdown.rb", "lib/rdoc/rd/block_parser.rb", "lib/rdoc/rd/inline_parser.rb"] are not files

Tasks: TOP => build
(See full trace by running task with --trace)

```

https://github.com/rdoc/rdoc/blob/master/rdoc.gemspec#L33 seems to cause this.
After removing this line, rake build succeeded.
Is this really necessary?

**Comment by hsbt** [comment]
You need to invoke `rake generate`

I added `rake generate` to dependency of `rake build` task with 
https://github.com/rdoc/rdoc/commit/c06cb00e86ee94e013e34fe27838f730ae94e8f0

**Comment by dogatana** [comment]
I didn't know (read) that.
Now it works fine, thank you.

**Comment by Apteryks** [comment]
@hsbt interestingly invoking 'gem build rdoc.gemspec' doesn't honor the added dependency... weird.
